// Standalone iOS probe: measures the STOCK Apple on-device foundation model on
// the real device, with the app's exact scoring prompts.
//
// Why a separate app and not a screen in MedAdvisor: importing FoundationModels
// for the system model and raising deploymentTarget would strand iOS 26 users —
// the exact reason the earlier Core AI branch was unmergeable. This target is
// never shipped and never touches the production app or its inference path.
//
// It answers what only a phone can answer:
//   - does the OS 27 system model (rebuilt, per Apple) grade better than the
//     macOS 26.3 one we measured at 54.3% accuracy / 75% over-score?
//   - the REAL context window, via SystemLanguageModel.contextSize
//   - refusals on default guardrails, on clinical content, on this OS
//   - tokens/sec, thermal state, and battery cost — the original motivation
//
// It deliberately does NOT score anything. It replays the 48 prompts verbatim
// from bench_prompts.json (generated by the Python harness) and records raw
// output. Scoring happens back on the Mac with app_scoring.py, so this result
// lands in the same table as Qwen, stock FM on macOS, and the adapter runs.
// Ground-truth labels are not in this app at all.

import FoundationModels
import SwiftUI
import UIKit

struct PromptItem: Codable {
    let id: String
    let prompt: String
}

struct CallResult: Codable {
    let id: String
    let ok: Bool
    var text: String?
    var errorKind: String?      // guardrail | contextWindow | other
    var errorDetail: String?
    let seconds: Double
    let outputTokens: Int?
    let thermalState: String
    let batteryLevel: Float
    /// Second-pass verification, only run when pass 1 answered "done".
    /// nil = not challenged (pass 1 was partial/missed, or the pass errored).
    var verifyRaw: String?
    var verifyRejected: Bool?
}

struct ProbeRun: Codable {
    var device: String
    var systemVersion: String
    var modelAvailability: String
    var contextSize: Int?
    var startedThermal: String
    var startedBattery: Float
    var finishedThermal: String
    var finishedBattery: Float
    var wallSeconds: Double
    var results: [CallResult]
}

func thermalName(_ s: ProcessInfo.ThermalState) -> String {
    switch s {
    case .nominal:  return "nominal"
    case .fair:     return "fair"
    case .serious:  return "serious"
    case .critical: return "critical"
    @unknown default: return "unknown"
    }
}

@MainActor
final class ProbeRunner: ObservableObject {
    @Published var status = "Idle"
    @Published var progress = 0.0
    @Published var running = false
    @Published var summary: String?
    @Published var fileURL: URL?

    func run() async {
        running = true
        summary = nil
        defer { running = false }

        UIApplication.shared.isIdleTimerDisabled = true          // GPU/ANE work needs foreground
        UIDevice.current.isBatteryMonitoringEnabled = true
        defer { UIApplication.shared.isIdleTimerDisabled = false }

        guard let url = Bundle.main.url(forResource: "bench_prompts", withExtension: "json"),
              let items = try? JSONDecoder().decode([PromptItem].self, from: Data(contentsOf: url))
        else { status = "bench_prompts.json missing from the bundle"; return }

        let model = SystemLanguageModel.default
        var availability = "available"
        if case .unavailable(let reason) = model.availability {
            availability = "unavailable(\(reason))"
            status = "Apple Intelligence unavailable: \(reason)"
            return
        }

        var ctx: Int?
        if #available(iOS 26.4, *) { ctx = model.contextSize }    // 4096 on macOS 26.3; Apple's WWDC26 session shows 8192

        var run = ProbeRun(
            device: UIDevice.current.model,
            systemVersion: UIDevice.current.systemVersion,
            modelAvailability: availability,
            contextSize: ctx,
            startedThermal: thermalName(ProcessInfo.processInfo.thermalState),
            startedBattery: UIDevice.current.batteryLevel,
            finishedThermal: "", finishedBattery: 0, wallSeconds: 0, results: [])

        let t0 = Date()
        for (i, item) in items.enumerated() {
            status = "\(i + 1)/\(items.count)  \(item.id)"
            progress = Double(i) / Double(items.count)

            // A fresh session per criterion: the app scores its 16 criteria
            // independently, and FoundationModels resets KV on divergence anyway.
            let session = LanguageModelSession(model: model)
            let options = GenerationOptions(sampling: .greedy, maximumResponseTokens: 180)
            let c0 = Date()
            do {
                let r = try await session.respond(to: item.prompt, options: options)

                // Second pass: challenge every "done". Only "done" is challenged,
                // so cost is ~1.4x calls rather than 2x, and a partial/missed
                // verdict can only be made worse by re-litigating it.
                //
                // A fresh session on purpose. FoundationModels resets KV on
                // divergence anyway, and reusing the graded session would let the
                // model see its own answer as conversation history and simply
                // agree with itself.
                var verifyRaw: String? = nil
                var verifyRejected: Bool? = nil
                if parsedVerdict(r.content) == "done" {
                    let evidence = parsedEvidence(r.content)
                    let vSession = LanguageModelSession(model: model)
                    let vOptions = GenerationOptions(sampling: .greedy,
                                                     maximumResponseTokens: 12)
                    do {
                        let v = try await vSession.respond(
                            to: verifyPrompt(scoringPrompt: item.prompt, evidence: evidence),
                            options: vOptions)
                        verifyRaw = v.content
                        verifyRejected = verificationRejects(v.content)
                    } catch {
                        // A failed challenge must not destroy a verdict: record it
                        // and keep pass 1 exactly as it stood.
                        verifyRaw = "ERROR: \(error)"
                        verifyRejected = false
                    }
                }
                // Token usage is NOT stable across SDK versions: macOS 26.3
                // exposes `response.usage`, an earlier iOS 27 SDK gated it to
                // 27.0, and the current one has no such member at all. tok/s is
                // a bonus metric — latency, refusals and the scores are what
                // this probe exists to measure — so it is simply dropped rather
                // than chased across betas.
                let outTokens: Int? = nil
                run.results.append(CallResult(
                    id: item.id, ok: true, text: r.content,
                    errorKind: nil, errorDetail: nil,
                    seconds: Date().timeIntervalSince(c0),
                    outputTokens: outTokens,
                    thermalState: thermalName(ProcessInfo.processInfo.thermalState),
                    batteryLevel: UIDevice.current.batteryLevel,
                    verifyRaw: verifyRaw, verifyRejected: verifyRejected))
            } catch let e as LanguageModelSession.GenerationError {
                let kind: String
                switch e {
                case .guardrailViolation:          kind = "guardrail"
                case .exceededContextWindowSize:   kind = "contextWindow"
                default:                           kind = "other"
                }
                run.results.append(CallResult(
                    id: item.id, ok: false, text: nil, errorKind: kind,
                    errorDetail: String(describing: e),
                    seconds: Date().timeIntervalSince(c0), outputTokens: nil,
                    thermalState: thermalName(ProcessInfo.processInfo.thermalState),
                    batteryLevel: UIDevice.current.batteryLevel))
            } catch {
                run.results.append(CallResult(
                    id: item.id, ok: false, text: nil, errorKind: "other",
                    errorDetail: String(describing: error),
                    seconds: Date().timeIntervalSince(c0), outputTokens: nil,
                    thermalState: thermalName(ProcessInfo.processInfo.thermalState),
                    batteryLevel: UIDevice.current.batteryLevel))
            }
        }

        run.wallSeconds = Date().timeIntervalSince(t0)
        run.finishedThermal = thermalName(ProcessInfo.processInfo.thermalState)
        run.finishedBattery = UIDevice.current.batteryLevel
        progress = 1

        let refusals = run.results.filter { $0.errorKind == "guardrail" }.count
        let toks = run.results.compactMap(\.outputTokens).reduce(0, +)
        let gen = run.results.map(\.seconds).reduce(0, +)
        summary = """
        \(run.results.filter(\.ok).count)/\(run.results.count) answered · \(refusals) refused
        context window: \(ctx.map(String.init) ?? "API unavailable")
        \(String(format: "%.1f", Double(toks) / max(gen, 0.001))) tok/s · \(String(format: "%.0f", run.wallSeconds))s total
        thermal \(run.startedThermal) → \(run.finishedThermal)
        battery \(Int(run.startedBattery * 100))% → \(Int(run.finishedBattery * 100))%
        """

        let enc = JSONEncoder()
        enc.outputFormatting = .prettyPrinted
        let out = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0]
            .appendingPathComponent("fm_probe_ios.json")
        try? enc.encode(run).write(to: out)
        fileURL = out
        status = "Done — share the JSON back to the Mac"
    }
}


// MARK: - Verification pass
//
// Two-pass scoring: grade as usual, then CHALLENGE every "done". Measured on
// Qwen 3.5-4B this cut over-scoring 31.2% -> 11.6%.
//
// Apple's model is the ideal shape for it: 46.7% over-score (14 of 30 absent
// behaviours wrongly credited) with 100% recall, so there are many false credits
// to remove and nothing correct to lose. If verification rescues it, the prize is
// no 3GB download and the Neural Engine instead of the GPU.
//
// NOTE: this uses two plain sessions rather than iOS 27's DynamicProfile. Profiles
// would share KV cache between the passes -- cheaper, NOT more accurate -- and the
// open question here is accuracy. Optimise only if the accuracy lands.

/// Pull the RESULT verdict out of a three-line reply.
func parsedVerdict(_ raw: String) -> String {
    for line in raw.split(whereSeparator: \.isNewline) {
        let low = line.lowercased().trimmingCharacters(in: .whitespaces)
        guard low.hasPrefix("result:") else { continue }
        let v = low.dropFirst("result:".count).trimmingCharacters(in: .whitespaces)
        if v.hasPrefix("done") || v.hasPrefix("met") { return "done" }
        if v.hasPrefix("partial") { return "partial" }
        return "missed"
    }
    return "missed"
}

/// Pull the EVIDENCE quote out of a three-line reply.
func parsedEvidence(_ raw: String) -> String {
    for line in raw.split(whereSeparator: \.isNewline) {
        let low = line.lowercased().trimmingCharacters(in: .whitespaces)
        guard low.hasPrefix("evidence:") else { continue }
        let text = line.trimmingCharacters(in: .whitespaces)
        return String(text.dropFirst("evidence:".count))
            .trimmingCharacters(in: CharacterSet(charactersIn: " \"'"))
    }
    return ""
}

/// The scoring prompt already carries the transcript and the criterion, so the
/// challenge is appended to it rather than rebuilt.
func verifyPrompt(scoringPrompt: String, evidence: String) -> String {
    scoringPrompt + """


    ---
    A grader judged the criterion above as "done", citing this evidence:
    "\(evidence)"

    Check that judgment strictly — your job is to catch a quote that does not \
    actually show the specific behavior being asked about.
    - A generic greeting, pleasantry, acknowledgement or sign-off ("take care", \
    "okay", "right", "no problem") does NOT demonstrate a specific behavior.
    - A quote showing a DIFFERENT behavior than the one asked about does NOT \
    count, even if it is good practice.
    - Something the PATIENT said never counts, whatever the speaker label claims.
    - If the quote genuinely shows this exact behavior, CONFIRM it — do not \
    reject a correct judgment.

    Reply with ONE word: CONFIRM or REJECT.
    """
}

/// True when the verifier rejects. Defaults to KEEPING the verdict on
/// unparseable output — a garbled reply must never silently destroy recall.
func verificationRejects(_ reply: String) -> Bool {
    let low = reply.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
    if low.hasPrefix("reject") || low.hasPrefix("no") { return true }
    if low.hasPrefix("confirm") || low.hasPrefix("yes") { return false }
    let head = String(low.prefix(40))
    return head.contains("reject") && !head.contains("confirm")
}

struct ContentView: View {
    @StateObject private var runner = ProbeRunner()
    @State private var sharing = false

    /// Read from the bundled resource so the button never claims a stale count.
    private var promptCount: Int {
        guard let url = Bundle.main.url(forResource: "bench_prompts", withExtension: "json"),
              let items = try? JSONDecoder().decode([PromptItem].self, from: Data(contentsOf: url))
        else { return 0 }
        return items.count
    }

    var body: some View {
        VStack(spacing: 22) {
            Text("Apple FM Probe").font(.largeTitle.bold())
            Text("Replays \(promptCount) benchmark prompts through the stock on-device model. No scoring happens here. Keep the app open — this takes about \(max(1, promptCount * 3 / 60)) minutes.")
                .font(.footnote).foregroundStyle(.secondary)
                .multilineTextAlignment(.center)

            if runner.running { ProgressView(value: runner.progress) }
            Text(runner.status).font(.caption.monospaced())

            if let s = runner.summary {
                Text(s).font(.callout.monospaced())
                    .padding().background(.quaternary, in: RoundedRectangle(cornerRadius: 12))
            }

            Button(runner.running ? "Running…" : "Run \(promptCount)-decision probe") {
                Task { await runner.run() }
            }
            .buttonStyle(.borderedProminent)
            .disabled(runner.running)

            if let url = runner.fileURL {
                Button("Share results JSON") { sharing = true }
                    .sheet(isPresented: $sharing) { ShareSheet(url: url) }
            }
        }
        .padding()
    }
}

struct ShareSheet: UIViewControllerRepresentable {
    let url: URL
    func makeUIViewController(context: Context) -> UIActivityViewController {
        UIActivityViewController(activityItems: [url], applicationActivities: nil)
    }
    func updateUIViewController(_ vc: UIActivityViewController, context: Context) {}
}

@main
struct FMProbeApp: App {
    var body: some Scene { WindowGroup { ContentView() } }
}
